version: '3.8'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - MINIMUM_NODE_VERSION=20
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    networks:
      - app_network

volumes:
  mongodb_data:
  minio_data:
  node_modules:

networks:
  app_network:
    driver: bridge
